### ISSUE TITLE
ant swallowed before saving causes an assert after you reload the game, spit it, and it flips upright

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#334] opened 2017-08-15 06:57 UTC
n/t

**Comment by rkettering** [comment] 2017-08-15 06:58
https://media.discordapp.net/attachments/271875323417591818/346910260390395906/frog_bug_1a.png

https://media.discordapp.net/attachments/271875323417591818/346910274500034561/frog_bug_1b.png

**Comment by DDR0** [comment] 2022-04-13 02:41
If this behaviour persists, it is probably related to https://github.com/frogatto/frogatto/issues/457 – however, I can't reproduce it here by the steps listed above.

**Comment by DDR0** [comment] 2022-04-13 03:28
After some testing myself and a brief discussion on #testing-and-feedback, none of us can recall seeing this recently. I am going to close it as I believe it has been fixed in the past half-decade, but we can reopen it if the issue crops up again.

**Closed by DDR0** 2022-04-13 03:28 UTC
Labels: Bug, Content/Object Development, Can't Reproduce
