### ISSUE TITLE
Game went completely mute after dying.

### ISSUE THREAD

**Issue by ActionJackalope** [frogatto/frogatto#289] opened 2016-07-20 07:46 UTC
I was in kitty factory and died by falling off a cliff.  Going back to the main menu didn't fix it.

Here's everything the game printed:

http://www.pasteall.org/72204

**Comment by ActionJackalope** [comment] 2016-07-30 17:46
It doesn't seem to require dying. It also triggers when transitioning between levels in Milgram's Castle. I got it when transitioning from central services to kitty factory, and also when entering central services from storerooms. It seems like it might be a gradual onset, as sounds start playing infrequently at first, then a level loads and they're gone altogether. Music is unaffected.

**Comment by ActionJackalope** [comment] 2016-07-30 17:51
Actually, it may not be a complete stop of all sounds. I loaded kitty factory at one point and the entire level was mute except the loop that followed the squeaky metal platforms. Then I died and that stopped playing too.

**Comment by rkettering** [comment] 2016-08-05 07:09
Here's an easier repro I've figured out.

start the game with --level kitty-factory.cfg   Walk to the left (you'll have to make a reasonably easy jump), and enter central-services.cfg, and then just walk back-and-forth between the two levels about a half dozen times, and then all sounds will cut out completely, but it'll be really noticeable when the ambient sounds die.

**Comment by rkettering** [comment] 2016-08-05 07:25
Testing with the following two commits:
Frogatto at:  a7a2fafa908f2bf5272e912e4ac3b25de66503f1
Anura at: https://github.com/anura-engine/anura/commit/554d1dd7aa94dc1d6326a50d576c4795f1d35c5c

Causes this to no longer reproduce.  That anura commit right before https://github.com/anura-engine/anura/commit/0146c7f570e487ce9fbdde8ac80c293f8eb40ce3  which I think may be the culprit.

**Comment by rkettering** [comment] 2016-08-05 08:29
>   <NotKrista>	Jetrel_bot: my guess is that the code was changed assuming that after fading out that the sample would be halted and freed. Obviously this isn't the case. The fix would be to call halt on the sample after the fade out time expires

**Comment by rkettering** [comment] 2016-08-07 00:31
Seems to be fixed as of:  https://github.com/anura-engine/anura/commit/72bec43f6ca0280bffad1515d47946a193f4ca83

**Closed by rkettering** 2016-08-07 00:31 UTC
Labels: Bug, Sound - Programmatic
