### ISSUE TITLE
Segmentation fault in Linux Mint XFCE 

### ISSUE THREAD

**Issue by mehmetulukaya** [frogatto/frogatto#392] opened 2018-10-14 17:56 UTC
Hi there ,

I just installed and try to run frogatto but it is gave error and  closed whole log are copied below:

Note: My system has got only 1GB ram and shared video card.

mintx@mintx-pc:~$ frogatto 
Frogatto engine version 1.3
LOOKING IN 'modules/frogatto/module.cfg': 1
EXPAND DATA PATHS
SET PREFERENCES PATH: ~/.frogatto/
PARSE ERROR: : Could not find file ./signature.cfg
EXPAND DATA PATHS
Preferences dir: /home/mintx/.frogatto/
get_dir(): /home/mintx/.frogatto/

OpenGL vendor: X.Org R300 Project
OpenGL version: 2.1 Mesa 18.0.5
OpenGL extensions: GL_AMD_shader_trinary_minmax GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_APPLE_packed_pixels GL_ARB_ES2_compatibility GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_copy_buffer GL_ARB_debug_output GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_robustness GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_sync GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_storage GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_window_pos GL_ATI_blend_equation_separate GL_ATI_draw_buffers GL_ATI_fragment_shader GL_ATI_separate_stencil GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_compiled_vertex_array GL_EXT_copy_texture GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_gpu_program_parameters GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_pixels GL_EXT_pixel_buffer_object GL_EXT_point_parameters GL_EXT_polygon_offset GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_subtexture GL_EXT_texture GL_EXT_texture3D GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_cube_map GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_object GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_snorm GL_EXT_vertex_array GL_EXT_vertex_array_bgra GL_IBM_multimode_draw_arrays GL_IBM_rasterpos_clip GL_IBM_texture_mirrored_repeat GL_INGR_blend_func_separate GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_MESA_pack_invert GL_MESA_texture_signed_rgba GL_MESA_window_pos GL_MESA_ycbcr_texture GL_NV_blend_square GL_NV_conditional_render GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_packed_depth_stencil GL_NV_primitive_restart GL_NV_texgen_reflection GL_NV_texture_barrier GL_NV_texture_env_combine4 GL_NV_texture_rectangle GL_OES_EGL_image GL_OES_read_format GL_S3_s3tc GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays 
GLSL Version: 1.20

Stencil bits: 8
JOYSTICKS: 0
initialized ttf
initialized 0 joysticks
SDL_GetVideoSurface()
LOADTEXTURE: backgrounds/loading_screen.png -> 0x1c4d910
failed to load image 'splash.jpg'
LOADING FONT: data/fonts.cfg -> modules/frogatto/data/fonts.cfg
LOADTEXTURE: gui/number_font.png -> 0x1c68850
LOADTEXTURE: gui/outline_font.png -> 0x1c63d50
LOADTEXTURE: gui/label_font.png -> 0x1c63c10
LOADTEXTURE: gui/dialog-font.png -> 0x1d27d50
CREATE OBJ: frogatto_playable
LOADTEXTURE: characters/frogatto-spritesheet1.png -> 0x1b0f060
LOADTEXTURE: characters/fat-frogatto-spritesheet1.png -> 0x1f33430
LOADTEXTURE: characters/frogatto-spritesheet5.png -> 0x1e3a870
LOADTEXTURE: characters/frogatto-spritesheet2.png -> 0x1f39600
LOADTEXTURE: characters/frogatto-spritesheet3.png -> 0x1f9fc50
LOADTEXTURE: characters/frogatto-spritesheet4.png -> 0x1fb48d0
LOADTEXTURE: characters/frogatto-spritesheet-idle.png -> 0x1fdb280
LOADTEXTURE: props/items.png -> 0x1fe6ab0
LOADTEXTURE: characters/frogatto-tongueB.png -> 0x1ff1370
LOADTEXTURE: effects/particles2.png -> 0x205f360
LOADTEXTURE: effects/powerup-fx.png -> 0x206a2b0
LOADTEXTURE: effects/homing-shot-init.png -> 0x2086230
LOADTEXTURE: effects/homing-shot-impact.png -> 0x20f3c70
LOADTEXTURE: characters/fat-frogatto-spritesheet3.png -> 0x2306310
LOADTEXTURE: characters/fat-frogatto-spritesheet4.png -> 0x2310700
LOADTEXTURE: gui/editor-tools.png -> 0x246ca60
LOADTEXTURE: gui/buttons-and-windows.png -> 0x2463010
LOADTEXTURE: gui/window-resize-grip.png -> 0x2472e20
LOADTEXTURE: gui/iphone_controls4.png -> 0x2479060
LOADTEXTURE: gui/ipad_controls.png -> 0x2475930
LOADTEXTURE: gui/inventory.png -> 0x2475550
LOADTEXTURE: gui/dialog.png -> 0x2473dc0
LOADTEXTURE: gui/dialog_font.png -> 0x2478f00
LOADTEXTURE: gui/hud.png -> 0x24802e0
LOADTEXTURE: gui/dialogue-box.png -> 0x2478370
LOADTEXTURE: gui/achievement-background.png -> 0x2481320
TEST absolute_path_test1 PASSED
TEST array_index PASSED
TEST base64_decode PASSED
TEST base64_encode PASSED
TEST base64_encode_bin PASSED
TEST color PASSED
TEST compression_test PASSED
TEST compute_relative_paths_test PASSED
TEST cost_path_search_function PASSED
TEST decimal_div PASSED
TEST decimal_from_string PASSED
TEST decimal_mul PASSED
TEST decimal_output PASSED
TEST directed_graph_function PASSED
TEST dot_precedence PASSED
TEST flatten_function PASSED
TEST formula PASSED
TEST formula_decimal PASSED
TEST formula_fn PASSED
TEST formula_function_default_args PASSED
TEST formula_in PASSED
ARGUMENT: (((x <- [0,1,2,3])))
ARGUMENT: (((x <- [0,1,2,3])))
ARGUMENT: (((x%2 = 1)))
TEST formula_list_comprehension PASSED
TEST formula_quotes PASSED
TEST formula_slice PASSED
TEST formula_test_recurse_sort PASSED
TEST formula_test_recursion PASSED
TEST formula_where_map PASSED
TEST json_base PASSED
TEST json_derive PASSED
TEST json_flatten PASSED
CALLING f...
{
	"value": {
		"a": 6,
		"b": {
			"a": 4,
			"z": 5
		}
	}
}TEST json_macro PASSED
TEST level_object_base64 PASSED
TEST map_function PASSED
TEST md5_test1 PASSED
TEST md5_test2 PASSED
TEST md5_test3 PASSED
TEST md5_test4 PASSED
TEST md5_test5 PASSED
TEST md5_test6 PASSED
TEST md5_test7 PASSED
TEST min_max_decimal PASSED
TEST modulo_operation PASSED
TEST rect PASSED
TEST rect_difference PASSED
TEST rect_intersect PASSED
TEST recursive_call_lambda PASSED
TEST short_circuit PASSED
TEST sqrt_function PASSED
TEST test_regex PASSED
TEST test_split_into_ints PASSED
TEST tokenizer_test PASSED
TEST variant_decimal PASSED
TEST variant_foreach PASSED
TEST weighted_graph_function PASSED
TEST where_scope_function PASSED
ALL 55 TESTS PASSED IN 47ms
FRAME BUFFER OBJECT IS SUPPORTED
FRAME BUFFER OBJECT IS SUPPORTED
in level constructor...
building...1268
done building...1268
LAYER -8 BUILT 0 tiles
LAYER -4 BUILT 0 tiles
LAYER -1 BUILT 0 tiles
LAYER 0 BUILT 0 tiles
LAYER 9 BUILT 0 tiles
LAYER 26 BUILT 0 tiles
LAYER 30 BUILT 0 tiles
LAYER 50 BUILT 0 tiles
done building tile_map...1269
done building hex_tile_map...1269
CREATE OBJ: dummy_gui_object
LOADTEXTURE: gui/dummy-hud.png -> 0x25c99e0
LOADTEXTURE: gui/iphone_controls5.png -> 0x2547310
LOADTEXTURE: gui/ipad_buttons.png -> 0x254a0a0
LOADTEXTURE: gui/ipad_buttons_pressed.png -> 0x254bee0
LOADTEXTURE: gui/iphone_controls.png -> 0x254f520
LOADTEXTURE: gui/iphone_controls3.png -> 0x2553930
LOADTEXTURE: gui/iphone_buttons.png -> 0x25ddaf0
LOADTEXTURE: gui/iphone_buttons_pressed.png -> 0x25df620
done level constructor: 65
CREATE OBJ: wood_door_titlescreen
LOADTEXTURE: props/door_titlescreen.png -> 0x25e3b50
PARSE ERROR: : Could not find file /home/mintx/.frogatto//save.cfg
PARSE ERROR: : Could not find file /home/mintx/.frogatto//save2.cfg
PARSE ERROR: : Could not find file /home/mintx/.frogatto//save3.cfg
PARSE ERROR: : Could not find file /home/mintx/.frogatto//save4.cfg
CREATE OBJ: text_controller
LOADTEXTURE: effects/particles.png -> 0x2681ce0
CREATE OBJ: level_controller_onetime
SET STARTING CYCLES: 0
Segmentation fault (core dumped)

**Comment by galegosimpatico** [comment] 2021-03-28 18:52
For Frogatto 3 you can possibly find some limited, unofficial troubleshooting support at the Discord server, but now it's off-topic at this issue tracker.

**Comment by DDR0** [comment] 2021-03-31 02:48
Aye; as I recall, 1.3 won't start on my Ubuntu these days either. Something's gone wrong with the package, unfortunately. :confused:

This is probably an issue to be brought up with the package maintainer, since it did work fine for a number of years. Additionally, as we can no longer support v1.3, I am closing this issue.

**Closed by DDR0** 2021-03-31 02:48 UTC

**Comment by inguin** [comment] 2022-04-25 12:49
In case anybody is still interested:

The issue is caused by a bug in sdl12-compat that was patched a few weeks ago: https://github.com/libsdl-org/sdl12-compat/commit/201670ec0a3324fd959acf6dadda51bd8041b3f8

For the time being, I've posted a workaround in the RPM Fusion Bugzilla: https://bugzilla.rpmfusion.org/show_bug.cgi?id=6252
