### ISSUE TITLE
Frogatto can't use tongue attack during running animation.

### ISSUE THREAD

**Issue by ghost** [frogatto/frogatto#131] opened 2014-05-16 03:27 UTC
Mind you, he can still use the tongue while _running_ in that he doesn't actually stop or even lose speed.  Rather, his animation turns into the walking animation while his velocity remains constant, then he returns to the running animation when his tongue finishes.

**Comment by DDR0** [comment] 2015-06-09 06:06
Confirmed 2015-06-08.

**Comment by rkettering** [comment] 2021-12-09 09:25
Seems to be fixed now.

**Closed by rkettering** 2021-12-09 09:25 UTC
Labels: Bug, Physics Edge-Case/Exploit
