### ISSUE TITLE
Esc menu crashes game

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#547] opened 2022-03-28 08:55 UTC
> Bug: Opening the menu via esc, navigating through it with arrow keys, and hitting enter crashes the game

**Comment by rkettering** [comment] 2022-03-28 08:55
I've been able to reproduce a crash going from `caustic-cauchemar.cfg` opening the menu, and clicking `return to titlescreen

**Comment by DDR0** [comment] 2022-04-13 03:36
Does this issue persist if you use the attack key to select the highlighted menu item instead?

The game usually crashes on exit; enter is the key to select the default action of the main menu which in this case is to exit the game. (That's why the button is a bit bolder. Although hot dang this is not intuitive to me, and I've been playing the game for a decade.)

**Comment by DDR0** [comment] 2022-04-13 03:50
The root cause of this bug will be fixed by fixing the engine's main menu.

**Closed by DDR0** 2022-04-13 03:50 UTC
Labels: Anura Issue
