### ISSUE TITLE
Game crashed when going outside from the first house

### ISSUE THREAD

**Issue by pampogokiraly** [frogatto/frogatto#421] opened 2020-12-10 09:26 UTC
This is the output from the terminal:
http://ix.io/2HoE

I am running frogatto on fully updated archlinux, installed from package.

**Comment by aarchetype** [comment] 2020-12-21 20:28
I ran into the same issue.
SIGSEGV arise from the string:
`glBlendEquationOES(GL_FUNC_REVERSE_SUBTRACT_OES);`
It can be avoided by various ways (e.g. place USE_GLES2 check before GL_OES_blend_subtract and then build with -DUSE_GLES2).
Keep in mind that archlinux package based on a latest stable version which was released 8(!) years ago.
I recommend you use frogatto-git package from AUR.
If you interested in patch for latest stable version I can help you.

**Comment by SanskritFritz** [comment] 2020-12-25 11:22
Thank you for that detailed explanation. I have built the -git package and yes the problem disappeared. Which is probably no surprise given how much has been changed under the hood. The new engine feels definitely slower at least on my fairly old hardware. Also there are quite a few glitches here and there so I'm very much interested in your patch you have offered. I would use the ABS to rebuild the stable package with your patch.

**Comment by aarchetype** [comment] 2020-12-26 08:02
> The new engine feels definitely slower at least on my fairly old hardware.
Well, that interesting.
In this case I can offer you very simple patch that just removes glBlendEquationOES:
[rm_glBlendEquationOES.patch.gz](https://github.com/frogatto/frogatto/files/5742825/rm_glBlendEquationOES.patch.gz)
(Github doesn't offer raw path so I gzipped it. Don't forget to `gzip -d` it).

**Comment by DDR0** [comment] 2021-04-01 22:00
> The new engine feels definitely slower at least on my fairly old hardware.
Unfortunately, the game is a lot more complex now - we've spent several years adding stuff to it now, and the newer game will need newer hardware.

As the issue is fixed in the current engine, I will mark this as closed for now. Thank you for providing the patch, aarchetype.

**Closed by DDR0** 2021-04-01 22:00 UTC
