### ISSUE TITLE
In-game menu appears to be unusable.

### ISSUE THREAD

**Issue by pbogdan** [frogatto/frogatto#397] opened 2019-01-04 07:36 UTC
Selecting any option from the in-game menu (brought up via the ESC key) causes the game to exit immediately.

**Comment by galegosimpatico** [comment] 2021-03-28 18:33
Close as "norepro"...

**Comment by galegosimpatico** [comment] 2021-03-28 18:34
Parts of this are "wontfix" because correspond to code that's going to be discarded because wholly replaced.

**Closed** 2021-03-30 07:59 UTC

**Comment by DDR0** [comment] 2021-03-31 02:29
Very curious, indeed, but I can't reproduce it either.
