### ISSUE TITLE
Coconuts (and other gravity-less ammo projectiles) can be given velocity by colliding with other projectiles.

### ISSUE THREAD

**Issue by rkettering** [frogatto/frogatto#548] opened 2022-04-12 20:03 UTC
The physics these objects have still include having 'feet', and I believe if something collides with the bottom of them, they'll get into a standing state, and go flying.   Either that or just colliding with the solid box of other ammo does the job.

**Comment by XrQ2Cat** [comment] 2022-04-28 18:36
Looks like a duplicate of #235

**Closed** 2022-07-02 03:30 UTC
