### ISSUE TITLE
Softlock in a swamp ambush

### ISSUE THREAD

**Issue by lasercatto** [frogatto/frogatto#712] opened 2023-09-01 00:14 UTC
Something I've been worried about has been confirmed - making a github issue for the sake of it; screenshot of said softlock at https://media.discordapp.net/attachments/920412269718953994/1146890184609235065/20230831213040_1.jpg?width=1118&height=629

**Comment by al0fdf** [comment] 2023-09-13 13:19
Duplicate of #700.

**Closed by al0fdf** 2023-09-13 13:19 UTC
Labels: Game-Breaking
