### ISSUE TITLE
Creature Field Guide in Inventory Causes Game to Hang When Inventory is Accessed

### ISSUE THREAD

**Issue by k8wu** [frogatto/frogatto#645] opened 2022-12-31 21:17 UTC
In current HEAD (running on top of Anura, also at HEAD), if you acquire the "Creature Field Guide" from the shop at the Tempo Village Docks, any attempts at opening your inventory hang the entire game to the point where you need to do a `kill -9` on the process. The only debug message given by default is: "libpng warning: iCCP: known incorrect sRGB profile"

I made a copy of that save file, and in the copy, I removed the line with "item_creature_field_guide" in it, then started the game and loaded that save file. Inventory now loads without any issue.

Tested on: Dell Latitude E5440 (with Intel Core i5-4310U CPU and 8 GiB memory) running Debian Bullseye 11.6, and recently recompiled Anura and an updated Frogatto module.

**Comment by DDR0** [comment] 2023-02-06 02:24
Ugh. I'll bet this is a probabilistic crash related to the widgets we use to build that screen. Thank you for the report.

**Comment by rkettering** [comment] 2023-07-10 07:18
Closing as a duplicate of:  https://github.com/frogatto/frogatto/issues/644

**Closed by rkettering** 2023-07-10 07:18 UTC
Labels: Anura Issue, Bug, Content/Object Development
